# Default values for hes-cmd-exe
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets:
   - name: image-secret
nameOverride: ""
fullnameOverride: ""

image:
  tag: ""

containers:
  - name: hes-avdhaan-v2
    image: "ap-mumbai-1.ocir.io/bmndcolr71u1/avdhaan-v2"
    imagePullPolicy: Always
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    livenessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 3
      failureThreshold: 3
      successThreshold: 1
      path: health
      healthcheckHttps: false
    readinessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 8
      timeoutSeconds: 3
      failureThreshold: 3
      successThreshold: 1
      path: health
    resources:
      limits:
        cpu: 800m
        memory: 1000Mi
      requests:
        cpu: 500m
        memory: 800Mi

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000
serviceAccount:
  # Specifies whether a service account should be created
  create: false
service:
  enabled: true
  type: ClusterIP
  port: 80

deployment:
  environment:
  
ingress:
  enabled: false



autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 90

nodeSelector:
  

tolerations: []

affinity: {}

